### ISSUE TITLE
Improve parsing 

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#264]
The parsing for the three different models (nist, mantid, sasview) is currently hard to read, and has lots of 'exec's.  This code should be reviewed and refactored, if appropriate, so that users can easily read to add new models in the future.

(feedback from @AndrewLister-STFC at retrospective number 1)

**Comment by AndrewLister-STFC** [comment]
I am proposing to separate the FittingProblem from the parsing.

This will give a single class for the Fitting Problem holding all the requisite attributes, and could combine with the suggestion in #271 so that the base parser class handles the file operations, while any parsers inherit this and simply implement a parse function.

(I'll also remove the execs/evals...)

**Comment by AndrewLister-STFC** [comment]
Something like this:

![image](https://user-images.githubusercontent.com/48282025/67970609-2ce7c900-fc03-11e9-9d31-84aceb53ea15.png)

**Comment by TOFarmer** [comment]
UML looks good.  I guess `get_parser` in your code snippet determines which parser is required based on filename?

**Comment by AndrewLister-STFC** [comment]
> UML looks good.  I guess get_parser in your code snippet determines which parser is required based on filename?

Yes, I think there is something in the code already to determine the type of file, so I will probably aim to use that for now.
