### ISSUE TITLE
Refactor table generation

### ISSUE THREAD

**Issue by wathen** [fitbenchmarking/fitbenchmarking#431]
Currently the ``controllers`` and ``parsers`` are setup using classes to ease extending FitBenchmarking. Whilst the table generation is concise, it should be done using classes to enable users and contributes a clear and usable way to add additional tables.

**Comment by AndrewLister-STFC** [comment]
I would suggest an architechture like this:
![image](https://user-images.githubusercontent.com/48282025/75567787-ffdce300-5a49-11ea-8c70-9fcb64fed841.png)

The calling function would then be able to add the string html output from `table.to_html()` to a page.
`to_html` would call `self.display_str()` to get the appropriate string representation of each result to put in the table.
Finally, `display_str()` could call `get_results()` to convert the result into a list of floats so that the abs/norm functionality is done in the base classes instance of `display_str()`.
The `LocalMinTable` class could override `display_str()` to allow the `bool (float)` output that it has.
