### ISSUE TITLE
Fitbenchmarking incorrectly parsing options file

### ISSUE THREAD

**Issue by jfowkes** [fitbenchmarking/fitbenchmarking#612]
**Description of the error**
Running fitbenchmarking on `examples/benchmark_problems/SIF` with the following `options.ini`:
```
[MINIMIZERS]
dfo: dfogn
minuit: minuit
[FITTING]
num_runs: 1
[PLOTTING]
make_plots: yes
[LOGGING]
external_output: no
```
results in `BUMPS`, `SCIPY` and `SCIPY_LS` being called in addition to the minimisers specified.

**Describe the expected result**
Only the specified minimisers should be called.

**Describe the actual result**
`BUMPS`, `SCIPY` and `SCIPY_LS` are also called despite not being specified.

**Suggested fix**
Only call the minimisers specified in the options file.

**Comment by tyronerees** [comment]
This is expected behaviour, although it is not intuitive and is not documented.  The options in `[MINIMIZERS]` are only accessed if the software is listed in `[SOFTWARE]`.  In the above example, as no software is specified, the defaults (`bumps`, `dfo`, `minuit`, `scipy`, and `scipy_ls`) are all run, with the default minimizers of `bumps`, `scipy` and `scipy_ls` being used. 

To make this clearer: 
- this should be clearly documented
- Fitting options should preceed Minimizers in the TOC of the docs
- Fitting should come before minimizers in the example ini files
- The file `options_template.ini` should be amended to highlight this is the expected behaviour

**Comment by jfowkes** [comment]
Agreed, at the very least `options_template.ini` should have a `[SOFTWARE]` section.
