### ISSUE TITLE
New option: maximum time

### ISSUE THREAD

**Issue by AndrewLister-STFC** [fitbenchmarking/fitbenchmarking#846]
Some softwares that have been added lately have a long runtime. We should have an option to limit the amount of time any minimizer can take.

This could be an option that just takes the maximum number of seconds, or it could take a string like "100s", "1m,40s","2h,15m",etc.

**Comment by Anders-Markvardsen** [comment]
Discussed this with @BenPetersRAL and with running tables for SasView, and this feature would be very useful. 

It should:

* by default be turned off, since danger that a user may unknowingly mis-interpret the output thinking that jobs stopped by natural causes and not by having a limit set
* Consider enabling it a command line option using as something like `fitbenchmarking --time-limit="100s"` in addition to or instead of an option `.ini`. 
* this issue should add an example of it being used with `fitbenchmarking --help`, either through command argument or from `.ini` file with a name something like `time_limit_execution.ini`
* Also add example of using this in main documentation

**Comment by Anders-Markvardsen** [comment]
A good example which illustrate the need for this feature is when running

```
fitbenchmarking -p examples/benchmark_problems/SAS_modelling/SASView_Simple_Shapes_1D
```

which takes on a on SCD cloud ubuntu 16 CPU 32GB so far an hour to run 3 out of 12 benchmark datasets. I don't think there is anything wrong with these benchmark datasets, we well just need a faster way of generating the table to get an quicker idea of which fitting engines are the slow coach.

In terms of implementation, probably we will need to kill fitting engines in their flow when overstretched their time limit since *in general* it is probably unlikely that we can terminate these at fixed time limit in any other way...

**Comment by AndrewLister-STFC** [comment]
The multithreading aproach seems unstable for some combinations. After discussion with collaborators from NAG, we agreed to try adding a wrapper on the function call to start a timer which will then cause NaN or an exception if it goes over the maximum time
